name: Release dev

on:
  push:
    branches:
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code-checks:
    name: Run code checks and quality tools
    uses: ./.github/workflows/_code_checks.yaml
    secrets:
      turbo-team: ${{ secrets.VERCEL_ORG_ID }}
      turbo-token: ${{ secrets.VERCEL_TOKEN }}
      db_uri: ${{ secrets.DATABASE_URL }}

  # migrate:
  #   name: Run the migrations on the database
  #   uses: ./.github/workflows/_migrate.yaml
  #   with:
  #     environment: Development
  #   secrets:
  #     db_uri: ${{ secrets.DATABASE_URL }}
