name: Check PR

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-commits:
    name: Lint commits
    uses: ./.github/workflows/_lint_commits.yaml

  code-checks:
    name: Run code checks and quality tools
    uses: ./.github/workflows/_code_checks.yaml
    secrets:
      turbo-team: ${{ secrets.VERCEL_ORG_ID }}
      turbo-token: ${{ secrets.VERCEL_TOKEN }}
      db_uri: ${{ secrets.DATABASE_URL }}
